Remove all dcgmproftester
canonical/dcgm-snap pull request #19
Opened 2024-09-13 15:30 UTC by gabrielcocenza

`dcgmproftester` has diffetent versions and needs libcuda which is not currently shipped in the snap, so it does not work out of the box. Moreover, some versions like the `dcgmproftester10` is not present in the arm64 version that breaks the build.

This PR removes all dcgmproftester until we have a more clear way on how to ship this service and keep the support for multi-arch

Closes: #18

2024-09-13 15:33 UTC, gabrielcocenza commented
Just to complement here are the logs proving that removing the `dcgmproftester` will make the build work for arm64:
```
2024-09-13 15:23:11.269 :: 2024-09-13 15:17:41.824 - library: libnvml_injection.so.1: unused library 'usr/lib/aarch64-linux-gnu/libnvml_injection.so.1.0'. (https://snapcraft.io/docs/linters-library)     
2024-09-13 15:23:11.271 :: 2024-09-13 15:17:41.826 - library: libnvperf_host.so: unused library 'usr/lib/aarch64-linux-gnu/libnvperf_dcgm_host.so'. (https://snapcraft.io/docs/linters-library)            
2024-09-13 15:23:11.272 :: 2024-09-13 15:17:41.829 pack_snap: output='.', compression='xz'                                                                                                                 
2024-09-13 15:23:11.274 :: 2024-09-13 15:17:41.832 pack_snap: check skeleton                                                                                                                               
2024-09-13 15:23:11.276 :: 2024-09-13 15:17:42.297 Creating snap package...                                                                                                                                
2024-09-13 15:23:11.277 :: 2024-09-13 15:17:42.301 Pack command: ['snap', 'pack', '--filename', 'dcgm_3.3.7_arm64.snap', '--compression', 'xz', PosixPath('/root/prime'), PosixPath('/root/project')]      
2024-09-13 15:23:11.279 :: 2024-09-13 15:23:03.007 Packed dcgm_3.3.7_arm64.snap                                                                                                                            
2024-09-13 15:23:11.291 Executing on host: lxc --project snapcraft config device show local:snapcraft-dcgm-on-arm64-for-arm64-259410                                                                       
2024-09-13 15:23:12.647 Executing on host: lxc --project snapcraft config device remove local:snapcraft-dcgm-on-arm64-for-arm64-259410 disk-/root/project                                                  
2024-09-13 15:23:14.507 Executing on host: lxc --project snapcraft stop local:snapcraft-dcgm-on-arm64-for-arm64-259410 
```

Currently, the [build](https://github.com/canonical/dcgm-snap/actions/runs/10840428244/job/30082690448?pr=15) is failing

2024-09-13 17:40 UTC, aieri requested changes
Can you please also remove the executables and related libraries? They are the greatest contributors to the size of the snap so we have a chance to trim a lot of MBs. See #2 

Also please update the description in snapcraft.yaml to mention the absence of these tools as we are diverging from upstream. Of course we have the main documentation PR pending, so a quick sentence is enough to ensure we don't forget.

2024-09-14 13:09 UTC, gabrielcocenza commented
Snap package now is only `25M` compared to `800M` that was before this change

2024-09-16 00:47 UTC, samuelallan72 submitted a review, later dismissed

2024-09-16 17:10 UTC, aieri approved these changes
+1, with some minor suggestions

2024-09-16 17:10 UTC, aieri commented on snap/local/scripts/remove_dcgmproftester.sh
> +for lib in "${FILES_TO_REMOVE[@]}"; do
non blocking nit: `dcgmproftester*` are not libs

2024-09-16 17:10 UTC, aieri commented on snap/local/scripts/remove_dcgmproftester.sh
> +echo "Removing libs that are missing cuda libs"
non blocking nit: I don't understand this line, I suggest rephrasing

2024-09-16 22:14 UTC, aieri approved these changes

2024-09-17 00:35 UTC, samuelallan72 approved these changes

2024-09-17 01:24 UTC, merged