Add a charm store icon for DCGM
canonical/dcgm-snap pull request #42
Opened 2024-10-16 17:13 UTC by aieri

This commit adds an icon for the snap. The icon is pulled from the
official logo[0] with the transparent background trimmed to 256x256px as
recommended in the snapcraft documentation[1]

[0] https://assets.nvidiagrid.net/ngc/logos/DCGM.png
[1] https://snapcraft.io/docs/snapcraft-yaml-schema#icon

2024-10-16 17:20 UTC, Deezzir requested changes
Blocked while waiting for NVIDIA's explicit approval

2024-10-29 13:27 UTC, gabrielcocenza approved these changes

2024-11-06 20:01 UTC, aieri commented
This is how the store will look after this change

![image](https://github.com/user-attachments/assets/66a152c1-6845-4aa5-b11b-75350368f893)


![image](https://github.com/user-attachments/assets/1efe5d4d-4543-40f1-95ac-df31cd6c6757)

2024-12-02 18:21 UTC, aieri commented
We have received approval from NVIDIA via email from Edrick Wong. We can go ahead and merge the icon.

2024-12-02 19:29 UTC, Deezzir approved these changes

2024-12-02 19:38 UTC, merged